# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PySLiM manual
author: Tskit Developers
copyright: "2021"
only_build_toc_files: true
# logo: logo.png
favicon: favicon.ico

execute:
  execute_notebooks: cache
  timeout: 300

launch_buttons:
  binderhub_url: ""

repository:
  url: https://github.com/tskit-dev/pyslim
  branch: main
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
    extra_extensions:
    - sphinx_copybutton
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.todo
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - sphinx_issues
    - sphinxarg.ext
    - IPython.sphinxext.ipython_console_highlighting

    config:
      html_theme: sphinx_book_theme
      html_theme_options:
        pygments_dark_style: monokai
        navigation_with_keys: false
        logo:
          text: |
            pyslim<br/>
            version __PYSLIM_VERSION__
      issues_github_path: tskit-dev/pyslim
      todo_include_todos: true
      intersphinx_mapping:
        python: ["https://docs.python.org/3/", null]
        tskit: ["https://tskit.dev/tskit/docs/stable", null]
        msprime: ["https://tskit.dev/msprime/docs/stable", null]
        tutorials: ["https://tskit.dev/tutorials/", null]
        stdpopsim: ["https://popsim-consortium.github.io/stdpopsim-docs/stable", null]
        numpy: ["https://numpy.org/doc/stable/", null]
      myst_enable_extensions:
      - colon_fence
      - deflist
