name: Docs

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:

  test:
    name: Build docs
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Cache conda and dependencies
        id: cache
        uses: actions/cache@v4.2.2
        env:
          # Increase this to reset the cache if the key hasn't changed.
          CACHE_NUM: 3
        with:
          path: |
            /usr/share/miniconda/envs/anaconda-client-env
            ~/osx-conda
            ~/.profile
          key: conda-v${{ env.CACHE_NUM }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3.1.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          activate-environment: anaconda-client-env
          python-version: "3.11"
          channels: conda-forge
          channel-priority: strict
          auto-update-conda: true

      - name: Install slim
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash -l {0} #We need a login shell to get conda
        run: |
          conda install --yes slim

      - name: Install uv and pip deps
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          pip install uv
          uv sync --locked --group docs --no-default-groups
          # Install current pyslim as editable to ensure we get the latest version
          uv pip install --system -e .

      - name: Build docs
        run: |
          source ~/.profile
          conda activate anaconda-client-env
          export PATH=$PWD/SLiM/Release:$PATH
          slim -v
          pip list
          cd docs && make
